### ISSUE TITLE
EFI目录呢？

### ISSUE THREAD

**Issue by nomco** [PIPIPIG233666/EFI-ROG-STRIX-B550-i-5900x-RX6650XT#1]
除了介绍别的东西呢？

**Comment by PIPIPIG233666** [comment]
> 除了介绍别的东西呢？

？ https://github.com/PIPIPIG233666/EFI-ROG-C8DH-5900x-RX6800XT/tree/EFI-ROG-C8DH-5900x-RX6800XT
